// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "analytic-collector": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=analytic-collector/api/design
// --out=$(GOPATH)/src/analytic-collector/api
// --version=v1.4.1

package app
